language: minimal

env:
  global:
    # Doctr deploy key for connectome-neuprint/neuprint-python
    - secure: "QqeH+hSDoiyLg21OjUGv7XUp9EqkaHHCC6ywyzCpTHZxmhXVYge3t7IxzhZ+fBXWZNicYeLn8ZceyJV/A6wm7a3Q3MksvHSQGCEeiX6HvnZ/gNTBUevIjnTlZ/vXNsThMl0VdgqQSpHWbpxJnvtStohPiHZc5ICDG9l8lFxUKTJi8pzphJVzo9ty8VK06VL8voQ9baV94SeqcBrLhnd413hhkpAfHJyoMO/GyDx3kj3i9PxJrwHFQ/XgFMGaeqnYFJxJYRrjdcvuoZWhKMQaRBMwFfUlAsfrHMUawZZhjUiSfR6RoE0TsnKGExQJM5y4zhVokyTq0T3tqqvdPzdwtncXjm1eQx2uzwn9lQJcqK0wqasDj1u8dG4PlFc5HvNSPceYxo8yeQQhditHhwfjRtnwdYadjqLotHuttPRZSdedHLnj6SMvuLpWQR6mfPi0a6GUXEUL0dfR7wa9nSIt3FMXQrsHfDMi0HldjLjRzlTIltTWXxeEOpooHqvn9szA+VNB5SBz0k8g+1lVEjeTM/okLtGlBioelOPtDeC7I6kPLTFHMd1Ty8ppgTj9+gsNNAcVxmdu3Uq+hMY8TgWRwf8R8q5pCR5gRm0x5ZyXms0zhlYeQCnmsu4UzGpLL0JLMXGZNfSY35uSyaOdv4aZc7Kme10aQnPkuks+y3r1eg8="

    # Valid NEUPRINT_APPLICATION_CREDENTIALS so the tests can run against neuprint.janelia.org.
    - secure: "XMTY3aqTL7WOKMOR5gmFWHm/a6ZfMXJq8p4Q8qAnXIGZdY5ChTCPgigwjXNyROhcvdPFRUe+SCB8s8J6S4c++1dslnk5c32QuMNlsfTtKVnVCiaYuUv8glu5/BihZkjNC9cTMu1PvA9eQisJ5skEtN6cISqEQ1NsUdzL/eoEvSLtz9nmIlm6pFavPr2XhnoQnmfMT+qh7LaY7mJf7t7xF2V9Ftz0w6yyBarBfAudqKnDHVbNZ+xvpmUVndTsL5Vq6Yd9oO6UMMHlRAzlFYHCxZxX2sJbaXeoYnYwnr8HR+v+1hU8i4C5U0HRsO0MKN/hK8T9C8Krwz9QL8rVNs7OpqOD/D10nwVYLpCdj1pFqaalX428n3LKndooqIOlK4lFDRl/9lT623K2rDzGzi1JvT2fKFVK0T6z1fUIU1JFHL4/misl97S7zJenX3P1TXiP3RpMIp5qzG5JUnqxhBtXsf8hBid8M5LjJs5NQpsI5nJ+kttnTh+DhjzCYlVqzvj2CQ3sfypcfQIr/WQWGdVebZ2WfsRDP2Gp3GvpQw4+xF/6TbtX3oOy2EpSudajJTPyVmvaOpYXVz80t501bm/8LwKS0/93zuRDIuzvP2ljRP901LWQU2sIcQaQCsE9YocZKBumco/8/D+E1UAJzGdFE55yX1Om4mjUoXrYSWj+mv0="

cache:
  directories: /home/travis/miniconda

before_cache:
  # Don't cache build artifacts, or any metadata files that changed in the conda prefix
  - conda clean --lock --index-cache
  - rm -rf /home/travis/miniconda/conda-bld
  - rm -rf /home/travis/miniconda/pkgs/cache
  - rm -rf /home/travis/miniconda/pkgs/neuprint-python*
  - rm -rf /home/travis/miniconda/pkgs/urls.txt
  - rm -rf /home/travis/miniconda/locks

git:
  # By default, travis uses git clone --depth=50,
  # which may not be deep enough to capture the most recent tag,
  # and the tags are necessary for our conda build.
  # Force a full clone.
  depth: false
  
install:
  - if [ ! -e $HOME/miniconda/bin/conda ]; then
      rm -rf $HOME/miniconda;
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
    fi
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels flyem-forge
  - conda update -q conda
  - conda install -y conda-build
  - conda install -c conda-forge codecov
  - conda info -a
  - conda install -y --file dependencies.txt
  - conda install -y --file docs/requirements.txt
  - conda install -y doctr

script:
  conda build conda-recipe

after_success:
  - set -e
  - export PYTHONPATH=$(pwd)
  - cd docs && make html && cd -
  - if [[ "${TRAVIS_BRANCH}" == "master" ]]; then
      doctr deploy --no-require-master --built-docs docs/build/html docs;
    else
      doctr deploy --no-require-master --built-docs docs/build/html "docs-$TRAVIS_BRANCH";
    fi
